server:
  port: 50051

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: forum_auth
  sslmode: disable

jwt:
  secret_key: "your-secret-key-here"
  ttl: 24 # hours 